<?php

return [
   'errors' => [
      'E001' => [
         'http_code' => 403,
         'status' => 'error',
         'code' => 'E001',
         'message' => 'E001 - User Atau Kata Sandi Salah',
      ],
      'E002' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E002',
         'message' => 'E002 - Anda Tidak Memiliki Otorisasi pada Menu Tersebut !',
      ],
      'E003' => [
         'http_code' => 401,
         'status' => 'error',
         'code' => 'E003',
         'message' => 'E003 - Token Expired',
      ],
      'E004' => [
         'http_code' => 403,
         'status' => 'error',
         'code' => 'E004',
         'message' => 'E004 - Token Invalid',
      ],
      'E005' => [
         'http_code' => 401,
         'status' => 'error',
         'code' => 'E005',
         'message' => 'E005 - Token Expired and Fail Renewing',
      ],
      'E006' => [
         'http_code' => 400,
         'status' => 'error',
         'code' => 'E006',
         'message' => 'E006 - Bad Request From User',
      ],
      'E007' => [
         'http_code' => 400,
         'status' => 'error',
         'code' => 'E007',
         'message' => 'E007 - User Terblokir, Hubungi Administrator',
      ],
      'E008' => [
         'http_code' => 400,
         'status' => 'error',
         'code' => 'E007',
         'message' => 'E007 - User Tidak Aktif, Hubungi Administrator',
      ],

      'E009' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E009',
         'message' => 'E009 - Gagal mengubah data !',
      ],

      'E010' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E010',
         'message' => 'E010 - Gagal menambah data !',
      ],

      'E011' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E011',
         'message' => 'E011 - Data tidak Tersedia !',
      ],
      'E012' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E012',
         'message' => 'E012 - Master Dokumen Prefix Belum Tersedia !',
      ],
      'E013' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E013',
         'message' => 'E013 - Harga Beli Harus Lebih Kecil Dari Harga Jual',
      ],
      'E014' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E014',
         'message' => 'E014 - Data Tidak Dapat Diubah, Dikarenakan Status Dokumen Tidak Memenuhi',
      ],
      'E015' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E015',
         'message' => 'E015 - Data Tidak Tersedia, Tanggal tidak boleh lebih dari 31 hari',
      ],
      'E016' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E016',
         'message' => 'E016 - Harap Pilih Meja Lainnya',
      ],
      
      'E017' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E017',
         'message' => 'E017 - Harap Pilih Meja Lainnya',
      ],
      'E018' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E018',
         'message' => 'E018 - Master Perusahaan Belum dilengkapi!',
      ],
      'E019' => [
         'http_code' => 200,
         'status' => 'error',
         'code' => 'E019',
         'message' => 'E019 - Gagal Delete Data',
      ],
      
      'E999' => [
         'http_code' => 500,
         'status' => 'error',
         'code' => 'E999',
         'message' => 'E999 - Error Tidak Diketahui',
      ],
      'E500' => [
         'http_code' => 500,
         'status' => 'error',
         'code' => 'E500',
         'message' => 'E500 - Terjadi Kesalah Komunikasi Server',
      ], 

      'E501' => [
         'http_code' => 500,
         'status' => 'error',
         'code' => 'E501',
         'message' => 'E501 - Terjadi Kesalahan Logging',
      ], 

   ],
   'success' => [
      'S000' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S000',
         'message' => 'S000 - Berhasil',
      ],
      'S001' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S001',
         'message' => 'S001 - Berhasil Login',
      ],
      'S002' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S002',
         'message' => 'S002 -Berhasil Tambah Data',
      ],
      'S003' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S003',
         'message' => 'S003 - Berhasil ubah data',
      ],
      'S004' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S004',
         'message' => 'S004 - Berhasil Delete Data',
      ],

      'S005' => [
         'http_code' => 200,
         'status' => 'success',
         'code' => 'S005',
         'message' => 'S005 - Berhasil Memperbaharui Token',
      ],
   ],
   'trans' => [
      'name' => 'Nama',
      'username' => 'UserName',
      'email' => 'Email',
      'mobile' => 'Nomor HP',
      'password' => 'Kata Sandi',
      'status' => 'Status',
      'users_acls_id' => 'Hak Akses',
      'sudo' => 'Superuser',
      'code' => 'Kode',
      'cost_price' => 'Harga Beli',
      'sell_price' => 'Harga Beli',
      'unit_id' => 'Satuan',
      'category_id' => 'Kategori',
      'quantity' => 'Kuantitas',
      'prefix' => 'Prefix',
      'docType' => 'Dokumen Type',
      // trans nama ACL
      'application' => 'Pengaturan Aplikasi',
      'master' => 'Data Induk',
      'purchase' => 'Pembelian',
      'sales' => 'Penjualan',
      'log_apps' => 'Log Aplikasi',
      'dashboard' => 'Dashboard',

      'master_acl' => 'Hak Akses',
      'master_category' => 'Master Kategori',
      'master_item' => 'Master Item',
      'master_unit' => 'Master Unit',
      'master_user' => 'Master Pengguna',
      'master_docPrefix' => 'Master Penomoran Dokumen',
      'master_sales_category' => 'Master Kategori Penjualan',
      'master_coa' => 'Master Chart Of Account',

      'purchase_order' => 'Order Pembelian',
      'transaction_purchase' => 'Transaksi Pembelian',
      'sales_order' => 'Order Penjualan',
      'transaction_sales' => 'Transaksi Penjualan',
      'membership' => 'Keanggotaan',
      'booking' => 'Pemesanan',

      'purchase_report' => 'Laporan Pembelian',
      'sales_report' => 'Laporan Penjualan',
      'overall_report' => 'Laporan Keseluruhan',

      'member_profile' => 'Profile Keanggotaan',
      'member_booking' => 'Profile Pemesanan',
      // 'application'=>'Menu Aplikasi',
      // 'master'=>'Menu Modul Master',
      // 'procurement'=>'Menu Modul Pembelian',
      // 'log_apps'=>'Data Log Aplikasi',
      // 'master_acl'=>'Master Hakakses Pengguna',
      // 'master_bank'=>'Master BANK',
      // 'master_category'=>'Master Kategori',
      // 'master_currency'=>'Master Mata Uang',
      // 'master_customer'=>'Master Pelanggan',
      // 'master_item'=>'Master Barang',
      // 'master_job'=>'Master Job',
      // 'master_supplier'=>'Master Pemasok',
      // 'master_unit'=>'Master Satuan',
      // 'master_user'=>'Master Pengguna',
      // 'procurement_requistion'=>'Permintaan Barang',
      // 'procurement_purchase'=>'Pembelian Barang',
      // 'procurement_invoice'=>'Faktur Pembelian Barang',
      // 'procurement_receipt'=>'Penerimaan Pembelian Barang',
      // 'project'=>'Data Proyek',

      // 'master_user' => 'Data Induk Pengguna',
      // 'master_supplier' => 'Data Induk Pemasok',
      // 'master_acl' => 'Data Induk Hak Akases',
      // 'master_superuser' => 'Data Induk Superuser',
      // 'master_unit' => 'Data Induk Satuan',
      // 'log_apps' => 'Log Aplikasi',
      // 'master_bank' => 'Data Induk Bank',
      // 'master_category' => 'Data Induk Kategori',
      // 'master_currency' => 'Data Induk Mata Uang',
      // 'master_customer' => 'Data Induk Pelanggan',
      // 'master_docPrefix' => 'Data Induk Prefix Document',
      // 'master_item' => 'Data Induk Barang',
      // 'procurement_requistion' => 'Pengadaan / Permintaan Pembelian',
      // 'procurement_purchase' => 'Pembelian',
      // 'procurement_invoice' => 'Faktur Pembelian',
      // 'procurement_receipt' => 'Peneriamaan Barang',

      'jurnal_umum' => 'Jurnal Umum',
      'cash_in' => 'Kas Masuk',
      'cash_out' => 'Kas Keluar',

      // ./trans nama ACL
      '_valid'=> 'Validasi',
      'log_apps_c'=>'Log App Create',
      'log_apps_d'=>'Log App Delete',
      'log_apps_e'=>'Log App Edit',
      'log_apps_i'=>'Log App Import',
      'log_apps_r'=>'Log App Read',
      'log_apps_u'=>'Log App Update',
      'master_acl_c'=>'Master ACL Create',
      'master_acl_d'=>'Master ACL Delete',
      'master_acl_e'=>'Master ACL Edit',
      'master_acl_i'=>'Master ACL Import',
      'master_acl_r'=>'Master ACL Read',
      'master_acl_u'=>'Master ACL Update',
      'master_superuser_c'=>'Master SuperUser Create',
      'master_superuser_d'=>'Master SuperUser Delete',
      'master_superuser_e'=>'Master SuperUser Edit',
      'master_superuser_i'=>'Master SuperUser Import',
      'master_superuser_r'=>'Master SuperUser Read',
      'master_superuser_u'=>'Master SuperUser Update',
      'master_supplier_c'=>'Master Supplier Create',
      'master_supplier_d'=>'Master Supplier Delete',
      'master_supplier_e'=>'Master Supplier Edit',
      'master_supplier_i'=>'Master Supplier Import',
      'master_supplier_r'=>'Master Supplier Read',
      'master_supplier_u'=>'Master Supplier Update',
      'master_user_c'=>'Master User Create',
      'master_user_d'=>'Master User Delete',
      'master_user_e'=>'Master User Edit',
      'master_user_i'=>'Master User Import',
      'master_user_r'=>'Master User Read',
      'master_user_u'=>'Master User Update',
      'nik' => 'NIK',
      'nama' => 'Nama',
      'place_birth' => 'Tempat Lahir',
      'date_birth' => 'Tanggal Lahir',
      'kota' => 'Kota',
      'provinsi' => 'Provinsi',
      'tax' => 'Pajak',
      'discount' => 'Diskon',
      'necessary' => 'Kepentingan',
      'total' => 'Total',
      'address' => 'Alamat',
      'date_booking'=> 'Tanggal Pemesanan',
      'customer'=> 'Nama Pemesan',
      'supplier'=> 'Nama Supplier',
      'supplier_code'=> 'Kode Supplier',
      'images'=> 'Gambar',
      'file'=> 'Gambar',
      'codeUser' => 'User Otorisasi',
      'codePass' => 'Password Otorisasi',
      'company' => 'Perusahaan',
      'mark_up' => 'Mark Up'
      
   ],

   'vMessage' => [
      'name.required' => 'Wajib mengisikan nama',
      'name.string' => 'Wajib mengisi nama dengan benar',
      'name.min' => 'Minimal :min karakter',
      'name.max' => 'Minimal :max karakter',
      'name.unique' => 'Nama Sudah dipakai',
      'nama.required' => 'Wajib mengisikan nama',
      'nama.string' => 'Wajib mengisi nama dengan benar',
      'nama.min' => 'Minimal :min karakter',
      'nama.max' => 'Minimal :max karakter',
      'nama.unique' => 'Nama Sudah dipakai',
      'customer.required' => 'Wajib mengisikan Nama Pemesan',
      'customer.string' => 'Wajib mengisi Nama Pemesan dengan benar',
      'customer.min' => 'Minimal :min karakter',
      'customer.max' => 'Minimal :max karakter',
      'customer.unique' => 'Nama Pemesan  Sudah dipakai',
      'supplier.required' => 'Wajib mengisikan Nama Supplier',
      'supplier.string' => 'Wajib mengisi Nama Supplier dengan benar',
      'supplier.min' => 'Minimal :min karakter',
      'supplier.max' => 'Minimal :max karakter',
      'supplier.unique' => 'Nama Supplier  Sudah dipakai',
      'supplier_code.required' => 'Wajib mengisikan Kode Supplier',
      'supplier_code.string' => 'Wajib mengisi Kode Supplier dengan benar',
      'supplier_code.min' => 'Minimal :min karakter',
      'supplier_code.max' => 'Minimal :max karakter',
      'supplier_code.unique' => 'Kode Supplier  Sudah dipakai',
      'supplier_code.exists' => 'Kode Supplier Tidak Ditemukan, Pastikan Kode Benar',
      'nik.required' => 'Wajib mengisikan NIK',
      'nik.string' => 'Wajib mengisi NIK dengan benar',
      'nik.min' => 'Minimal :min karakter',
      'nik.max' => 'Minimal :max karakter',
      'nik.unique' => 'NIK Sudah dipakai',
      'code.required' => 'Wajib mengisikan Kode',
      'code.string' => 'Wajib mengisi kode dengan benar',
      'code.min' => 'Minimal :min karakter',
      'code.max' => 'Minimal :max karakter',
      'code.unique' => 'Kode Sudah dipakai',
      'date_booking.required' => 'Wajib mengisikan Tanggal Pemesanan',
      'date_booking.date' => 'Wajib mengisi Tanggal Pemesanan dengan benar',
      'date_booking.after' => 'Silahkan pilih Keesokan harinya',
      'date_booking.unique' => 'Tanggal Pemesanan Sudah dipakai',
      'place_birth.required' => 'Wajib mengisikan Tempat Lahir',
      'place_birth.string' => 'Wajib mengisi kode dengan benar',
      'place_birth.min' => 'Minimal :min karakter',
      'place_birth.max' => 'Minimal :max karakter',
      'place_birth.unique' => 'Tempat Lahir Sudah dipakai',

      'date_birth.required' => 'Wajib mengisikan Tanggal Lahir',
      'date_birth.string' => 'Wajib mengisi kode dengan benar',
      'date_birth.min' => 'Minimal :min karakter',
      'date_birth.max' => 'Minimal :max karakter',
      'date_birth.unique' => 'Tanggal Lahir Sudah dipakai',
      'provinsi.required' => 'Wajib mengisikan Provinsi',
      'provinsi.string' => 'Wajib mengisi kode dengan benar',
      'provinsi.min' => 'Minimal :min karakter',
      'provinsi.max' => 'Minimal :max karakter',
      'provinsi.unique' => 'Provinsi Sudah dipakai',

      'kota.required' => 'Wajib mengisikan Kota',
      'kota.string' => 'Wajib mengisi kode dengan benar',
      'kota.min' => 'Minimal :min karakter',
      'kota.max' => 'Minimal :max karakter',
      'kota.unique' => 'Kota Sudah dipakai',

      'image.image' => 'Format Gambar tidak sesuai',
      'image.required' => 'Wajib Menambahkan gambar',
      'image.min' => 'Minimal ukuran gambar :max KB',
      'image.max' => 'Maksimal ukuran gambar :max KB',
      'image.mimes' => 'Format Gambar tidak sesuai',

      'file.image' => 'Format Gambar tidak sesuai',
      'file.required' => 'Wajib Menambahkan gambar',
      'file.min' => 'Minimal ukuran gambar :max KB',
      'file.max' => 'Maksimal ukuran gambar :max KB',
      'file.mimes.*' => 'Format Gambar tidak sesuai',
      'file.uploaded' => 'Format Gambar tidak sesuai',
      // 'file.*' => 'Gambar tidak sesuai',

      'cost_price.required' => 'Wajib mengisikan harga beli',
      'cost_price.string' => 'Wajib mengisi harga beli dengan benar',
      'cost_price.min' => 'Minimal :min karakter',
      'cost_price.max' => 'Minimal :max karakter',
      'cost_price.between' => 'Minimal :min & Maximal :max karakter',
      'sell_price.required' => 'Wajib mengisikan harga jual',
      'sell_price.string' => 'Wajib mengisi harga jual dengan benar',
      'sell_price.min' => 'Minimal :min karakter',
      'sell_price.max' => 'Minimal :max karakter',
      'sell_price.between' => 'Minimal :min & Maximal :max karakter',
      'unit_id.required' => 'Wajib mengisikan Satuan',
      'unit_id.string' => 'Wajib mengisi Satuan dengan benar',
      'unit_id.min' => 'Minimal :min karakter',
      'unit_id.max' => 'Minimal :max karakter',
      'unit_id.digit_between' => 'Minimal :min & Maximal :max karakter',
      'quantity.required' => 'Wajib mengisikan Kuantitas',
      'quantity.string' => 'Wajib mengisi Kuantitas dengan benar',
      'quantity.min' => 'Minimal :min karakter',
      'quantity.max' => 'Minimal :max karakter',
      'quantity.digit_between' => 'Minimal :min & Maximal :max karakter',
      'username.required' => 'Wajib mengisikan username',
      'username.string' => 'Wajib mengisi usename dengan benar',
      'username.min' => 'Minimal :min karakter',
      'username.max' => 'Minimal :max karakter',
      'username.unique' => 'Username telah digunakan',
      'email.required' => 'Wajib mengisikan email',
      'email.max' => 'Maximal :max Karakter',
      'email.unique' => 'Email telah digunakan',
      'mobile.required' => 'Wajib mengisikan nomor HP ',
      'mobile.unique' => 'Nomor HP sudah terpakai di member lain ',
      'mobile.numeric' => 'Wajib menggunakan angka',
      'mobile.min' => 'Minimal :min karakter',
      'mobile.max' => 'Maximal :max karakter',
      'mobile.between' => 'Minimal :min & Maximal :max karakter',
      'mobile.digits_between' => 'Minimal :min & Maximal :max karakter',
      'password.required' => 'Wajib mengisikan password ',
      'password.confirmed' => 'Konfirmasi kata sandi tidak sama',
      'password.min' => 'Minimal :min karakter',
      'status.required' => 'Wajib mengisikan ',
      'status.boolean' => 'Periksa isian status',
      'users_acls_id.required' => 'Wajib mengisikan ',
      'users_acls_id.exists' => 'Periksa isian hak akses',
      'sudo.required' => 'Wajib mengisikan ',
      'sudo.boolean' => 'Periksa isian superuser',
      'file.image' => 'Gambar bukan file',
      'file.mimes' => 'Format gambar harus JPEG/JPG/BMP/PNG',
      'file.max' => 'Ukuran gambar maximal 2MB',
      'log_apps_c.boolean'=> "Inputan tidak Sesuai",
      'log_apps_d.boolean'=> "Inputan tidak Sesuai",
      'log_apps_e.boolean'=> "Inputan tidak Sesuai",
      'log_apps_i.boolean'=> "Inputan tidak Sesuai",
      'log_apps_r.boolean'=> "Inputan tidak Sesuai",
      'log_apps_u.boolean'=> "Inputan tidak Sesuai",
      'master_acl_c.boolean'=> "Inputan tidak Sesuai",
      'master_acl_d.boolean'=> "Inputan tidak Sesuai",
      'master_acl_e.boolean'=> "Inputan tidak Sesuai",
      'master_acl_i.boolean'=> "Inputan tidak Sesuai",
      'master_acl_r.boolean'=> "Inputan tidak Sesuai",
      'master_acl_u.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_c.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_d.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_e.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_i.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_r.boolean'=> "Inputan tidak Sesuai",
      'master_superuser_u.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_c.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_d.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_e.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_i.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_r.boolean'=> "Inputan tidak Sesuai",
      'master_supplier_u.boolean'=> "Inputan tidak Sesuai",
      'master_user_c.boolean'=> "Inputan tidak Sesuai",
      'master_user_d.boolean'=> "Inputan tidak Sesuai",
      'master_user_e.boolean'=> "Inputan tidak Sesuai",
      'master_user_i.boolean'=> "Inputan tidak Sesuai",
      'master_user_r.boolean'=> "Inputan tidak Sesuai",
      'master_user_u.boolean'=> "Inputan tidak Sesuai",
      'prefix.required' => 'Wajib mengisikan Prefix',
      'prefix.string' => 'Wajib mengisi Prefix dengan benar',
      'prefix.min' => 'Minimal :min karakter',
      'prefix.max' => 'Minimal :max karakter',
      'prefix.unique' => 'Prefix Sudah dipakai',
      'docType.required' => 'Wajib mengisikan docType',
      'docType.string' => 'Wajib mengisi docType dengan benar',
      'docType.min' => 'Minimal :min karakter',
      'docType.max' => 'Minimal :max karakter',
      'docType.unique' => 'docType Sudah dipakai',
      'codeUser.required' => 'Wajib mengisikan Code User',
      'codePass.required' => 'Wajib mengisikan Code Password',


      'mark_up.required' => 'Wajib mengisikan mark_up',
      'mark_up.string' => 'Wajib mengisi mark_up dengan benar',
      'mark_up.min' => 'Minimal :min karakter',
      'mark_up.max' => 'Minimal :max karakter',
      'mark_up.unique' => 'mark_up Sudah dipakai',


   ]
];
